---
- name: Setup HTTP Application
  hosts: _http_static
  become: true
  vars:
    ansible_user: ubuntu
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  tasks:

  - name: Create a ext4 FS on /dev/xvdb
    community.general.filesystem:
      dev: /dev/xvdb
      fstype: ext4

  - name: Mount /dev/xvdb to /var/www/html
    ansible.posix.mount:
      path: /var/www/html
      src: /dev/svdb
      fstype: ext4
      state: present

  - name: Clean var/www/html
    file:
      state: "{{item}}"
      path: /var/www/html
    with_items:
      - absent
      - directory

  - name: Clone repo to /var/www/html
    ansible.builtin.git:
      repo: 'https://bitbucket.org/dptrealtime/html-web-app.git'
      dest: /var/www/html