---
- name: Setup HTTP Application
  hosts: _http_static
  become: true
  vars:
    ansible_user: ubuntu
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  tasks:

  - name: Create a ext4 FS on /dev/xvdb
    community.general.filesystem:
      dev: /dev/xvdb
      fstype: ext4

  - name: Mount /dev/xvdb to /var/www/html
    ansible.posix.mount:
      path: /var/www/html
      src: /dev/svdb
      fstype: ext4
      state: present

  - name: Clean var/www/html
    file:
      state: "{{item}}"
      path: /var/www/html
    with_items:
      - absent
      - directory

  - name: Clone repo to /var/www/html
    ansible.builtin.git:
      repo: 'https://bitbucket.org/dptrealtime/html-web-app.git'
      dest: /var/www/html

  - name: Download CloudWatch agent deb
    ansible.builtin.get_url:
      url: "https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb"
      dest: /tmp/cloudwatch-agent.deb

  - name: Install Cloudwatch agent
    ansible.builtin.apt:
      deb:  /tmp/cloudwatch-agent.deb    

  - name: Generate Cloudwatch config
    ansible.builtin.template:
      src: cloudwatch_config.json.j2
      dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json

  - name: Start Cloudwatch agent
    ansible.builtin.systemd:
      name: amazon-cloudwatch-agent
      state: started
      enabled: true

  